### ISSUE TITLE
XMonad.Prompt does not support font fallback

### ISSUE THREAD

**Issue by NickHu** [xmonad/xmonad-contrib#208]
### Problem Description

This is most noticable with the `XMonad.Prompt.Unicode` module. Many of the Unicode glyphs are not visible in any single font, and the way we would like to achieve coverage is by matching in sequence through a font preference list.
I would have expected something like

```haskell
myXPConfig = def {
  font = "xft:Terminus, xft:Noto Emoji"
}
```

to work, but this appears to instead crash XMonad when the prompt is raised.

I suspect font fallback is just unimplemented; `XMonad.Util.Font` does mention `fallBack`, but I don't think it has the semantics above.

Suggestions for fonts to use for `XMonad.Prompt.Unicode` would also be good - Symbola seems okay aside from its regular text being very ugly.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by laMudri** [comment]
Should this be an issue on the XMonad core? In my experience, no part of XMonad supports fallback fonts, so I'm guessing the root of the problem is in XMonad itself.

**Comment by geekosaur** [comment]
The core doesn't use fonts and therefore doesn't support them in any sense. xmonad-contrib can be built with support for X11-xft, but the contrib module would still need to be coded for fallback support; and if contrib wasn't built with xft support, fallback fonts aren't a thing. (This is all X11, not xmonad. It's somewhat ancient.)

People whose only exposure to X11 is indirect via Gtk or Qt mostly don't realize that those toolkits *exist* because X11 doesn't support all the fancy stuff they consider "fundamental", like fallback fonts.

**Comment by Vonfry** [comment]
Any process on this issue? I have the same issue. The fallback fonts cannot work such as tab and prompt.

**Comment by iliayar** [comment]
I've succeeded with moving [xmobar fallback fonts logic](https://github.com/jaor/xmobar/blob/master/src/Xmobar/X11/MinXft.hsc). Seems like it may add performance overhead. It also requires manual bindings from the Xft library, because https://hackage.haskell.org/package/X11-xft doesn't have binding for vital `XftCharExists` function. I still have some strange behavior with Prompt sometimes.

**Comment by muellert** [comment]
This might be one of the reasons why I'm holding off with Xmonad. I was interested before, but have lots of foreign language files etc., which are all gibberish at best, when viewed in window titles.

**Comment by slotThe** [comment]
On Fri, Sep 03 2021 16:56, muellert wrote:
> This might be one of the reasons why I'm holding off with Xmonad. I
> was interested before, but have lots of foreign language files etc.,
> which are all gibberish at best, when viewed in window titles.

Unless you're talking about window decorations, then status bars can
usually display these titles just fine (and xmonad can send them
properly encoded); this thread is specifically about the prompt

**Comment by geekosaur** [comment]
In particular, window titles should be fixed by the recent change to default to Xft fonts instead of `-misc-fixed`, and IIRC those do support font fallback.

**Comment by slotThe** [comment]
> I've succeeded with moving [xmobar fallback fonts logic](https://github.com/jaor/xmobar/blob/master/src/Xmobar/X11/Text.hs). Seems like it may add performance overhead. It also requires manual bindings from the Xft library, because https://hackage.haskell.org/package/X11-xft doesn't have binding for vital `XftCharExists` function. ~I still have some strange behavior with Prompt sometimes.~
>
> P.S. It's [here](https://github.com/iliayar/xmonad-contrib/tree/feature/fallback-fonts). Should I PR?

@iliayar yes please!  The bindings could perhaps be part of X11 (I haven't looked at the code at all yet).  Any performance problems will probably have to be ironed out before this is merged, but this is much easier with a concrete PR that one can talk about.

Looking forward to it!

**Comment by liskin** [comment]
> The bindings could perhaps be part of X11

I think we might also consider offerring to take the X11-xft under the xmonad ubrella. Clemens has been struggling to find time to maintain it (it's been more than a year since I sent him a patch for the flipped colors, a couple months since he applied the patched, and a couple weeks since he got his hackage account back, but it still isn't released).

**Comment by slotThe** [comment]
> I think we might also consider offerring to take the X11-xft under the xmonad ubrella. Clemens has been struggling to find time to maintain it (it's been more than a year since I sent him a patch for the flipped colors, a couple months since he applied the patche, and a couple weeks since he got his hackage account back, but it still isn't released).

I think that would be pretty neat; it would certainly make https://github.com/xmonad/xmonad-contrib/pull/646 a much smaller change on the contrib side.  Since you have already had contact to Clemens, would you be prepared to ask him?

In the meantime, would it be appropriate that we host a fork and require that when building xmonad?  At least stack lets you specify e.g. a GitHub URL so I'm sure Cabal has a similar feature [^1]

[^1]: What I'm worried about here is the "months" and https://github.com/xmonad/xmonad-contrib/pull/646 being stuck in PR limbo during that time

**Comment by liskin** [comment]
> I think that would be pretty neat; it would certainly make #646 a much smaller change on the contrib side. Since you have already had contact to Clemens, would you be prepared to ask him?

I sent him an e-mail.

> In the meantime, would it be appropriate that we host a fork and require that when building xmonad? At least stack lets you specify e.g. a GitHub URL so I'm sure Cabal has a similar feature [1](#user-content-fn-1-1aaa3a4ca447e9f8dcfef576e1ef62c0)

I would prefer to avoid making building xmonad any more complicated than it already is. Let's give it a week or two and then discuss what to do next.

**Comment by geekosaur** [comment]
Cabal supports github and other URLs in the `cabal.project` file (more or less its equivalent of `stack.yaml`). But I'm with @liskin on holding off before resorting to it in either stack or cabal.

**Comment by liskin** [comment]
So there's https://github.com/xmonad/X11-xft now, feel free to open a PR with the missing bindings against it. We can then (let GitHub Actions) release it to Hackage.

(I'll be busy with other stuff for the next couple of days or a week, so please don't expect this to be all done next week.)
